version: "3.8"

services:
    front:
        container_name: "front"
        build:
            context: .
            dockerfile: deployments/docker/node/dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
        tty: true