FROM node:16.15-alpine3.15 as build

WORKDIR /app

COPY . /app

ARG GIT_SHORT_SHA
ENV GIT_SHORT_SHA=$GIT_SHORT_SHA

RUN yarn install

RUN yarn run build:dev

# RUN rm ./build/static/js/*.js.map

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]