const cloudImgUrlBase = `https://sprodm.uni247.xyz/images/`;
const cloudImgUrlBaseV3 = process.env.REACT_APP_IMG_ROOT;

const cloudImg = {
  img: {
    boost_bg: cloudImgUrlBase + 'Boost/front_bg.svg',
    breadcrumbArrow: cloudImgUrlBase + 'Breadcrumb/breadcrumbArrow.svg',
    breadcrumbArrowDisable_bk:
      cloudImgUrlBase + 'Breadcrumb/breadcrumbArrowDisable_bk.svg',
    Bagde_live: cloudImgUrlBase + 'Event/Badge-live.svg',
    Bagde_live_e73030: cloudImgUrlBase + 'Event/Bagde_live_e73030.svg',
    Date_999: cloudImgUrlBase + 'Event/Date_999.svg',
    Favourite: cloudImgUrlBase + 'Event/Favourite.svg',
    Time_2A86FE: cloudImgUrlBase + 'Event/Time_2A86FE.svg',
    Time_999: cloudImgUrlBase + 'Event/Time_999.svg',
    GoBack: cloudImgUrlBase + 'GoBack.svg',
    burger_cross: cloudImgUrlBase + 'Header/burger_cross.svg',
    HeaderLoadingGif: cloudImgUrlBase + 'Header/HeaderLoadingGif.gif',
    Menu1_f5e7c0: cloudImgUrlBase + 'Header/Menu1_f5e7c0.svg',
    Ticket_wh: cloudImgUrlBase + 'Header/Ticket_wh.svg',
    openMenu: cloudImgUrlBase + 'Header/open-menu.svg',
    openMenuActive: cloudImgUrlBase + 'Header/open-menu-1.svg',
    Basketball_333: cloudImgUrlBase + 'Home/Basketball_333.svg',
    Basketball_999: cloudImgUrlBase + 'Home/Basketball_999.svg',
    Basketball_ddc38e: cloudImgUrlBase + 'Home/Basketball_ddc38e.svg',
    Baseball_333: cloudImgUrlBase + 'Home/Baseball_333.svg',
    Baseball_999: cloudImgUrlBase + 'Home/Baseball_999.svg',
    Baseball_ddc38e: cloudImgUrlBase + 'Home/Baseball_ddc38e.svg',
    Badminton_333: cloudImgUrlBase + 'Home/Badminton_333.svg',
    Badminton_999: cloudImgUrlBase + 'Home/Badminton_999.svg',
    Badminton_ddc38e: cloudImgUrlBase + 'Home/Badminton_ddc38e.svg',
    Cycling_333: cloudImgUrlBase + 'Home/Cycling_333.svg',
    Cycling_999: cloudImgUrlBase + 'Home/Cycling_999.svg',
    Cycling_ddc38e: cloudImgUrlBase + 'Home/Cycling_ddc38e.svg',
    Darts_333: cloudImgUrlBase + 'Home/Darts_333.svg',
    Darts_999: cloudImgUrlBase + 'Home/Darts_999.svg',
    Darts_ddc38e: cloudImgUrlBase + 'Home/Darts_ddc38e.svg',
    Formula_1_333: cloudImgUrlBase + 'Home/Formula_1_333.svg',
    Formula_1_999: cloudImgUrlBase + 'Home/Formula_1_999.svg',
    Formula_1_ddc38e: cloudImgUrlBase + 'Home/Formula_1_ddc38e.svg',
    Golf_333: cloudImgUrlBase + 'Home/Golf_333.svg',
    Golf_999: cloudImgUrlBase + 'Home/Golf_999.svg',
    Golf_ddc38e: cloudImgUrlBase + 'Home/Golf_ddc38e.svg',
    Greyhound_333: cloudImgUrlBase + 'Home/Greyhound_333.svg',
    Greyhound_999: cloudImgUrlBase + 'Home/Greyhound_999.svg',
    Greyhound_ddc38e: cloudImgUrlBase + 'Home/Greyhound_ddc38e.svg',
    Ice_hockey_333: cloudImgUrlBase + 'Home/Ice_hockey_333.svg',
    Ice_hockey_999: cloudImgUrlBase + 'Home/Ice_hockey_999.svg',
    Ice_hockey_ddc38e: cloudImgUrlBase + 'Home/Ice_hockey_ddc38e.svg',
    Indoor_soccer_333: cloudImgUrlBase + 'Home/Indoor_soccer_333.svg',
    Indoor_soccer_999: cloudImgUrlBase + 'Home/Indoor_soccer_999.svg',
    Indoor_soccer_ddc38e: cloudImgUrlBase + 'Home/Indoor_soccer_ddc38e.svg',
    Motogp_333: cloudImgUrlBase + 'Home/Motogp_333.svg',
    Motogp_999: cloudImgUrlBase + 'Home/Motogp_999.svg',
    Motogp_ddc38e: cloudImgUrlBase + 'Home/Motogp_ddc38e.svg',
    Snooker_333: cloudImgUrlBase + 'Home/Snooker_333.svg',
    Snooker_999: cloudImgUrlBase + 'Home/Snooker_999.svg',
    Snooker_ddc38e: cloudImgUrlBase + 'Home/Snooker_ddc38e.svg',
    Table_tennis_333: cloudImgUrlBase + 'Home/Table_tennis_333.svg',
    Table_tennis_999: cloudImgUrlBase + 'Home/Table_tennis_999.svg',
    Table_tennis_ddc38e: cloudImgUrlBase + 'Home/Table_tennis_ddc38e.svg',
    Volleyball_333: cloudImgUrlBase + 'Home/Volleyball_333.svg',
    Volleyball_999: cloudImgUrlBase + 'Home/Volleyball_999.svg',
    Volleyball_ddc38e: cloudImgUrlBase + 'Home/Volleyball_ddc38e.svg',
    Virtual_sport_333: cloudImgUrlBase + 'Home/Virtual_sport_333.svg',
    Virtual_sport_999: cloudImgUrlBase + 'Home/Virtual_sport_999.svg',
    Virtual_sport_ddc38e: cloudImgUrlBase + 'Home/Virtual_sport_ddc38e.svg',
    Esport_333: cloudImgUrlBase + 'Home/Esport_333.svg',
    Esport_999: cloudImgUrlBase + 'Home/Esport_999.svg',
    Esport_ddc38e: cloudImgUrlBase + 'Home/Esport_ddc38e.svg',
    Horse_racing_333: cloudImgUrlBase + 'Home/Horse_racing_333.svg',
    Horse_racing_999: cloudImgUrlBase + 'Home/Horse_racing_999.svg',
    Horse_racing_ddc38e: cloudImgUrlBase + 'Home/Horse_racing_ddc38e.svg',
    Aussie_rules_333: cloudImgUrlBase + 'Home/Aussie_rules_333.svg',
    Aussie_rules_999: cloudImgUrlBase + 'Home/Aussie_rules_999.svg',
    Aussie_rules_ddc38e: cloudImgUrlBase + 'Home/Aussie_rules_ddc38e.svg',
    American_football_333: cloudImgUrlBase + 'Home/American_football_333.svg',
    American_football_999: cloudImgUrlBase + 'Home/American_football_999.svg',
    American_football_ddc38e: cloudImgUrlBase + 'Home/American_football_ddc38e.svg',
    Cricket_333: cloudImgUrlBase + 'Home/Cricket_333.svg',
    Soccer_333: cloudImgUrlBase + 'Home/Soccer_333.svg',
    Cricket_999: cloudImgUrlBase + 'Home/Cricket_999.svg',
    Cricket_ddc38e: cloudImgUrlBase + 'Home/Cricket_ddc38e.svg',
    Cricket_fff: cloudImgUrlBase + 'Home/Cricket_fff.svg',
    Football_333: cloudImgUrlBase + 'Home/Football_333.svg',
    Football_999: cloudImgUrlBase + 'Home/Football_999.svg',
    Football_999_black: cloudImgUrlBase + 'Home/Football_999_black.svg',
    Football_ddc38e: cloudImgUrlBase + 'Home/Football_ddc38e.svg',
    Tennis_333: cloudImgUrlBase + 'Home/Tennis_333.svg',
    Tennis_999: cloudImgUrlBase + 'Home/Tennis_999.svg',
    Tennis_ddc38e: cloudImgUrlBase + 'Home/Tennis_ddc38e.svg',
    iconCateArrow_666: cloudImgUrlBase + 'iconCateArrow_666.svg',
    Arrow_wh: cloudImgUrlBase + 'LeftSideBar/Arrow_wh.svg',
    Arrow_333: cloudImgUrlBase + 'LeftSideBar/Arrow_333.svg',
    help_wh: cloudImgUrlBase + 'LeftSideBar/help_wh.svg',
    inplay_666: cloudImgUrlBase + 'LeftSideBar/inplay_666.svg',
    upcoming: cloudImgUrlBase + 'LeftSideBar/upcoming.svg',
    Loading_no_logoForBk: cloudImgUrlBase + 'Loading_no_logoForBk.gif',
    Loading_questionMark_cdcdcd:
      cloudImgUrlBase + 'Loading_questionMark_cdcdcd.svg',
    Done_bk: cloudImgUrlBase + 'Manual/Manual_bk/Done_bk.svg',
    Manual_10th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_10th.gif',
    Manual_11th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_11th.png',
    Manual_12th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_12th.gif',
    Manual_1st: cloudImgUrlBase + 'Manual/Manual_bk/Manual_1st.png',
    Manual_2nd: cloudImgUrlBase + 'Manual/Manual_bk/Manual_2nd.png',
    Manual_3rd: cloudImgUrlBase + 'Manual/Manual_bk/Manual_3rd.png',
    Manual_4th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_4th.gif',
    Manual_5th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_5th.gif',
    Manual_6th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_6th.gif',
    Manual_7th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_7th.png',
    Manual_8th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_8th.gif',
    Manual_9th: cloudImgUrlBase + 'Manual/Manual_bk/Manual_9th.gif',
    Next_bk: cloudImgUrlBase + 'Manual/Manual_bk/Next_bk.svg',
    Arrow_ddc38e: cloudImgUrlBase + 'Markets/Arrow_ddc38e.svg',
    first: cloudImgUrlBase + 'Markets/first.svg',
    Rise1_wh: cloudImgUrlBase + 'Markets/Rise1_wh.svg',
    riskArrowGold: cloudImgUrlBase + 'Markets/riskArrowGold.svg',
    riskArrowGrey: cloudImgUrlBase + 'Markets/riskArrowGrey.svg',
    second: cloudImgUrlBase + 'Markets/second.svg',
    third: cloudImgUrlBase + 'Markets/third.svg',
    winnerStar: cloudImgUrlBase + 'Markets/winner-star.svg',
    newWindow_wh: cloudImgUrlBase + 'newWindow_wh.svg',
    notificationDevelopToolMode:
      cloudImgUrlBase + 'Notification/notification_developToolMode.png',
    NotificationLoading:
      cloudImgUrlBase + 'Notification/notification-loading.gif',
    xx_wh: cloudImgUrlBase + 'Notification/xx_wh.svg',
    no_event: cloudImgUrlBase + 'no_event.svg',
    Close3: cloudImgUrlBase + 'Orderlist/Close3.svg',
    DropDown_ddc08c: cloudImgUrlBase + 'Orderlist/DropDown_ddc08c.svg',
    itemDropDown_wh: cloudImgUrlBase + 'Orderlist/itemDropDown_wh.svg',
    orderlistLoading: cloudImgUrlBase + 'Orderlist/orderlistLoading.gif',
    Back2_wh: cloudImgUrlBase + 'OrderSlip/Back2_wh.svg',
    Close1_333: cloudImgUrlBase + 'OrderSlip/Close1_333.svg',
    banner_bg_cricket:
      cloudImgUrlBase + 'PopularBackground/banner_bg_cricket.webp',
    banner_bg_soccer:
      cloudImgUrlBase + 'PopularBackground/banner_bg_soccer.webp',
    banner_bg_tennis:
      cloudImgUrlBase + 'PopularBackground/banner_bg_tennis.svg',
    banner_bg_tennis_m: cloudImgUrlBase + 'PopularBackground/tennis_m.png',
    Date_wh: cloudImgUrlBase + 'PopularBackground/Date_wh.svg',
    popular_icon_ddc08c:
      cloudImgUrlBase + 'PopularBackground/popular_icon_ddc08c.svg',
    Time_wh: cloudImgUrlBase + 'PopularBackground/Time_wh.svg',
    portraitScreen: cloudImgUrlBase + 'portraitScreen.svg',
    iconLiveCount: cloudImgUrlBase + 'QuickLink/iconLiveCount.svg',
    SwitchTradesAndTime:
      cloudImgUrlBase + 'SortedIconBlock/SwitchTradesAndTime.svg',
    Sorted_trades_fff:
      cloudImgUrlBase + 'SortedIconBlock/Sorted_trades_fff.svg',
    Sorted_trades_ddc08c:
      cloudImgUrlBase + 'SortedIconBlock/Sorted_trades_ddc08c.svg',
    Sorted_Time_fff: cloudImgUrlBase + 'SortedIconBlock/Sorted_Time_fff.svg',
    Sorted_Time_ddc08c:
      cloudImgUrlBase + 'SortedIconBlock/Sorted_Time_ddc08c.svg',
    reflective: cloudImgUrlBase + 'reflective.gif',
    filters: cloudImgUrlBase + 'Statement/filters.svg',
    history_wh: cloudImgUrlBase + 'Statement/history_wh.svg',
    loadingIcon: cloudImgUrlBase + 'Statement/loading.gif',
    no_order_wh: cloudImgUrlBase + 'Statement/no-order_wh.svg',
    BackToTop: cloudImgUrlBase + 'Statement/top.svg',
    eye_closed: cloudImgUrlBase + 'Usermenu/eye_closed.svg',
    eye_opened: cloudImgUrlBase + 'Usermenu/eye_opened.svg',
    statement_ddc38e: cloudImgUrlBase + 'Usermenu/statement_ddc38e.svg',
    chatroom_999: cloudImgUrlBase + 'Visual/chatroom_999.svg',
    LMT_838383: cloudImgUrlBase + 'Visual/LMT_838383.svg',
    microphone_999: cloudImgUrlBase + 'Visual/microphone_999.svg',
    //stream
    streamError_ddc08c: cloudImgUrlBase + 'streamError_ddc08c.svg',
    streaming_333: cloudImgUrlBase + 'streaming_333.svg',
    streaming_ddc08c: cloudImgUrlBase + 'streaming_ddc08c.svg',
    streaming_fullscreen: cloudImgUrlBase + 'streaming-fullscreen.svg',

    streaming_fancy_arrow: cloudImgUrlBase + 'streaming-fancy-arrow.svg',
    streaming_hamburger:
      cloudImgUrlBase + '../assets/images/Visual/streaming-hamburger.svg',
    streaming_keyboard_arrow:
      cloudImgUrlBase + '../assets/images/Visual/streaming-keyboard-arrow.svg',
    streaming_close_icon:
      cloudImgUrlBase + '../assets/images/Visual/streaming-close-icon.svg',

    warning_wh: cloudImgUrlBase + 'warning_wh.svg',
    CloseTag: cloudImgUrlBase + 'CloseTag.svg',
    HpSwipe: cloudImgUrlBase + 'HpSwipe.svg',
    nothing_start: cloudImgUrlBase + 'nothing_star.svg',
    shopping_bag: cloudImgUrlBase + 'shopping-bag.svg',

    // v3
    CloseTag_999: cloudImgUrlBaseV3 + 'CloseTag_999.svg',
    CloseTag_c4c4c4: cloudImgUrlBaseV3 + 'CloseTag_c4c4c4.svg',
    CloseTag_8ecfff: cloudImgUrlBaseV3 + 'CloseTag_8ecfff.svg',
    CloseTag_e8963f: cloudImgUrlBaseV3 + 'CloseTag_e8963f.svg',
    HpSwipe: cloudImgUrlBaseV3 + 'HpSwipe.svg',
    suspendV3: cloudImgUrlBaseV3 + 'suspendV3.svg',
    Soccer_black_v3: cloudImgUrlBaseV3 + 'Soccer_black_v3.svg',
    Soccer_fff_v3: cloudImgUrlBaseV3 + 'Soccer_fff_v3.svg',
    Tennis_black_v3: cloudImgUrlBaseV3 + 'Tennis_black_v3.svg',
    Tennis_fff_v3: cloudImgUrlBaseV3 + 'Tennis_fff_v3.svg',
    Baseball_black_v3: cloudImgUrlBaseV3 + 'Baseball_black_v3.svg',
    Baseball_fff_v3: cloudImgUrlBaseV3 + 'Baseball_fff_v3.svg',
    Basketball_black_v3: cloudImgUrlBaseV3 + 'Basketball_black_v3.svg',
    Basketball_fff_v3: cloudImgUrlBaseV3 + 'Basketball_fff_v3.svg',
    Volleyball_black_v3: cloudImgUrlBaseV3 + 'Volleyball_black_v3.svg',
    Volleyball_fff_v3: cloudImgUrlBaseV3 + 'Volleyball_fff_v3.svg',
    history_blue: cloudImgUrlBaseV3 + 'history_blue.svg',
    volleyball_black: cloudImgUrlBaseV3 + 'volleyball_black.svg',
    volleyball_white: cloudImgUrlBaseV3 + 'volleyball_white.svg',

    //v3 lmt footer
    v3_lmt_chart: cloudImgUrlBaseV3 + 'v3-lmt-chart.svg',
    v3_lmt_live_blue: cloudImgUrlBaseV3 + 'v3-lmt-live-blue.svg',
    v3_lmt_live: cloudImgUrlBaseV3 + 'v3-lmt-live.svg',
    v3_lmt_live_999: cloudImgUrlBaseV3 + 'v3_lmt_live_999.svg',
    v3_lmt_live_c4c4c4: cloudImgUrlBaseV3 + 'v3_lmt_live_c4c4c4.svg',
    v3_lmt_lmt: cloudImgUrlBaseV3 + 'v3-lmt-lmt.svg',
    v3_lmt_lmt_c4c4c4: cloudImgUrlBaseV3 + 'v3_lmt_lmt_c4c4c4.svg',
    v3_lmt_lmt_999: cloudImgUrlBaseV3 + 'v3_lmt_lmt_999.svg',
    v3_lmt_news: cloudImgUrlBaseV3 + 'v3-lmt-news.svg',
    v3_widget_analyze: cloudImgUrlBaseV3 + 'v3_widget_analyze.svg',
    v3_widget_analyze_c4c4c4:
      cloudImgUrlBaseV3 + 'v3_widget_analyze_c4c4c4.svg',
    v3_widget_analyze_999: cloudImgUrlBaseV3 + 'v3_widget_analyze_999.svg',

    // v3 widget analyze
    v3_widget_cross: cloudImgUrlBaseV3 + 'v3_widget_cross.svg',
    v3_widget_lineup_c4c4c4: cloudImgUrlBaseV3 + 'v3_widget_lineup_c4c4c4.svg',
    v3_widget_lineup_wh: cloudImgUrlBaseV3 + 'v3_widget_lineup_wh.svg',
    v3_widget_live_table_c4c4c4:
      cloudImgUrlBaseV3 + 'v3_widget_live_table_c4c4c4.svg',
    v3_widget_live_table_wh: cloudImgUrlBaseV3 + 'v3_widget_live_table_wh.svg',
    v3_widget_match_commentary_c4c4c4:
      cloudImgUrlBaseV3 + 'v3_widget_match_commentary_c4c4c4.svg',
    v3_widget_match_commentary_wh:
      cloudImgUrlBaseV3 + 'v3_widget_match_commentary_wh.svg',
    v3_widget_match_statistics_c4c4c4:
      cloudImgUrlBaseV3 + 'v3_widget_match_statistics_c4c4c4.svg',
    v3_widget_match_statistics_wh:
      cloudImgUrlBaseV3 + 'v3_widget_match_statistics_wh.svg',

    //market
    product_arrow_v3: cloudImgUrlBaseV3 + 'product-arrow-v3.svg',

    Loading_no_logoForV3: cloudImgUrlBaseV3 + 'Loading_no_logoForV3.gif',
    //header
    v3_market_header_back: cloudImgUrlBaseV3 + 'v3-market-header-back.svg',

    v3_market_header_orderlist_fff:
      cloudImgUrlBaseV3 + 'v3_market_header_orderlist_fff.svg',
    v3_market_header_orderlist_333:
      cloudImgUrlBaseV3 + 'v3_market_header_orderlist_333.svg',
    // v3_market_arrow: cloudImgUrlBaseV3 + 'v3-market-arrow.svg',
    v3_market_arrow_fff: cloudImgUrlBaseV3 + 'v3_market_arrow_fff.svg',
    v3_market_arrow_333: cloudImgUrlBaseV3 + 'v3_market_arrow_333.svg',
    v3_header_burger: cloudImgUrlBaseV3 + 'v3-header-burger.svg',
    v3_header_add_value: cloudImgUrlBaseV3 + 'v3-header-add-value.svg',
    v3_header_avatar: cloudImgUrlBaseV3 + 'v3-header-avatar.jpeg',

    // footer
    casino_v2: cloudImgUrlBaseV3 + 'india_casino.svg',
    home_v2: cloudImgUrlBaseV3 + 'india_home.svg',
    inplay_v2: cloudImgUrlBaseV3 + 'india_cricket.svg',
    statement_v2: cloudImgUrlBaseV3 + 'india_statement.svg',
    my_v2: cloudImgUrlBaseV3 + 'india_my.svg',
    RNG_v2: cloudImgUrlBaseV3 + 'india_RNG.svg',

    // VERSION 3 order slip
    v3_orderslip_arrow: cloudImgUrlBaseV3 + 'v3-orderslip-arrow.svg',
    v3_orderslip_arrow_fff: cloudImgUrlBaseV3 + 'v3_orderslip_arrow_fff.svg',
    v3_orderslip_arrow_333: cloudImgUrlBaseV3 + 'v3_orderslip_arrow_333.svg',
    v3_orderslip_clear_c4c4c4:
      cloudImgUrlBaseV3 + 'v3_orderslip_clear_c4c4c4.svg',
    v3_orderslip_close: cloudImgUrlBaseV3 + 'v3-orderslip-close.svg',
    v3_orderslip_reduce: cloudImgUrlBaseV3 + 'v3-orderslip-reduce.svg',
    v3_orderslip_trash: cloudImgUrlBaseV3 + 'v3-orderslip-trash.svg',
    v3_shopping_bag: cloudImgUrlBaseV3 + 'v3-shopping-bag.svg',
    v3_shopping_bag_333: cloudImgUrlBaseV3 + 'v3_shopping_bag_333.svg',
    v3_shopping_bag_fff: cloudImgUrlBaseV3 + 'v3_shopping_bag_fff.svg',
    v3_PlaceBetLoading: cloudImgUrlBaseV3 + 'v3_PlaceBetLoading.svg',
    // v3_orderslip_statement: cloudImgUrlBaseV3 + 'orderslip-statement-icon.svg',
    // League_quicklink_v3: cloudImgUrlBaseV3 + 'League_quicklink_v3.svg',
    // v3 quicklink

    League_quicklink_v3: cloudImgUrlBaseV3 + 'League_quicklink_v3.png',
    v3_quicklink_fifa_icon: cloudImgUrlBaseV3 + 'v3_quicklink_fifa_icon.png',
    homepage_quicklink_v3: cloudImgUrlBaseV3 + 'quicklink-homepage-v3.svg',
    VN_quicklink_v3: cloudImgUrlBaseV3 + 'VN.png',
    vleague1_quicklink_v3: cloudImgUrlBaseV3 + 'vleague1.png',
    vleague2_quicklink_v3: cloudImgUrlBaseV3 + 'vleague2.png',
    vietnamcup_quicklink_v3: cloudImgUrlBaseV3 + 'vietnamcup.png',
    supercup_quicklink_v3: cloudImgUrlBaseV3 + 'supercup.png',
    simulated_quicklink_v3: cloudImgUrlBaseV3 + 'simulated@4x.svg',
    Soccer_quicklink_v3: cloudImgUrlBaseV3 + 'Soccer_quicklink_v3.svg',
    Cricket_quicklink_v3: cloudImgUrlBaseV3 + 'Cricket_quicklink_v3.svg',
    Tennis_quicklink_v3: cloudImgUrlBaseV3 + 'Tennis_quicklink_v3.svg',
    Basketball_quicklink_v3: cloudImgUrlBaseV3 + 'Basketball_quicklink_v3.svg',
    American_football_quicklink_v3: cloudImgUrlBaseV3 + 'American_football_quicklink_v3.svg',
    Mma_quicklink_v3: cloudImgUrlBaseV3 + 'Mma_quicklink_v3.svg',
    Aussie_rules_quicklink_v3: cloudImgUrlBaseV3 + 'Aussie_rules_quicklink_v3.svg',
    Baseball_quicklink_v3: cloudImgUrlBaseV3 + 'Baseball_quicklink_v3.svg',
    Badminton_quicklink_v3: cloudImgUrlBaseV3 + 'Badminton_quicklink_v3.svg',
    Cycling_quicklink_v3: cloudImgUrlBaseV3 + 'Cycling_quicklink_v3.svg',
    Darts_quicklink_v3: cloudImgUrlBaseV3 + 'Darts_quicklink_v3.svg',
    Golf_quicklink_v3: cloudImgUrlBaseV3 + 'Golf_quicklink_v3.svg',
    Formula_1_quicklink_v3: cloudImgUrlBaseV3 + 'Formula_1_quicklink_v3.svg',
    Greyhound_quicklink_v3: cloudImgUrlBaseV3 + 'Greyhound_quicklink_v3.svg',
    Ice_hockey_quicklink_v3: cloudImgUrlBaseV3 + 'Ice_hockey_quicklink_v3.svg',
    Indoor_soccer_quicklink_v3:
      cloudImgUrlBaseV3 + 'Indoor_soccer_quicklink_v3.svg',
    Motogp_quicklink_v3: cloudImgUrlBaseV3 + 'Motogp_quicklink_v3.svg',
    Snooker_quicklink_v3: cloudImgUrlBaseV3 + 'Snooker_quicklink_v3.svg',
    Table_tennis_quicklink_v3:
      cloudImgUrlBaseV3 + 'Table_tennis_quicklink_v3.svg',
    Volleyball_quicklink_v3: cloudImgUrlBaseV3 + 'Volleyball_quicklink_v3.svg',
    Horse_racing_quicklink_v3:
      cloudImgUrlBaseV3 + 'Horse_racing_quicklink_v3.svg',
    Virtual_sport_quicklink_v3:
      cloudImgUrlBaseV3 + 'Virtual_sport_quicklink_v3.svg',
    ESport_quicklink_v3: cloudImgUrlBaseV3 + 'ESport_quicklink_v3.svg',
    Casino_quicklink_v3: cloudImgUrlBaseV3 + 'Casino_quicklink_v3.svg',
    Boxing_quicklink_v3: cloudImgUrlBaseV3 + 'boxing-glove.png',
    Handball_quicklink_v3: cloudImgUrlBaseV3 + 'handball.png',
    Bowls_quicklink_v3: cloudImgUrlBaseV3 + 'Bowls.png',
    Basketball_3x3_quicklink_v3: cloudImgUrlBaseV3 + 'Basketball_3x3.svg',
    Beach_volley_quicklink_v3: cloudImgUrlBaseV3 + 'Beach_Volley.png',
    Futsal_quicklink_v3: cloudImgUrlBaseV3 + 'Futsal.png',
    Squash_quicklink_v3: cloudImgUrlBaseV3 + 'Squash.png',
    Rugby_quicklink_v3: cloudImgUrlBaseV3 + 'rugby-ball.png',
    Field_hockey_quicklink_v3: cloudImgUrlBaseV3 + 'field_hockey.png',
    Favourite_quicklink_v3: cloudImgUrlBaseV3 + 'Favourite_quicklink_v3.svg',
    S_S_LAZIO_quicklink_v3: cloudImgUrlBaseV3 + 'S_S_LAZIO_quicklink_v3.svg',
    Italian_Serie_A_quicklink_v3: cloudImgUrlBaseV3 + 'Italian_Serie_A_quicklink_v3.svg',
    Spanish_LaLiga_quicklink_v3: cloudImgUrlBaseV3 + 'Spanish_LaLiga_quicklink_v3.svg',

    //v3 five-league quicklink
    Highlights_quicklink_v3: cloudImgUrlBaseV3 + 'highlights.png',
    // AFF_quicklink_v3: cloudImgUrlBaseV3 + 'AFF.png',
    // Bundesleague_quicklink_v3: cloudImgUrlBaseV3 + 'bundesliga.png',
    // LaLiga_quicklink_v3: cloudImgUrlBaseV3 + 'laliga.png',
    // Ligue1_quicklink_v3: cloudImgUrlBaseV3 + 'ligue1.png',
    // PremiumLeague_quicklink_v3: cloudImgUrlBaseV3 + 'Premiumleague.png',
    // Ipl_quicklink_v3: cloudImgUrlBaseV3 + 'Indian_Premier_League_Official_Logo.png',
    // Fih_quicklink_v3: cloudImgUrlBaseV3 + 'FIH_Pro_League_Logo.png',
    // Mls_quicklink_v3: cloudImgUrlBaseV3 + 'MLS.svg',
    // Cwcq_quicklink_v3: cloudImgUrlBaseV3 + 'CWC_Q_Logo.svg',
    // Theashes_quicklink_v3: cloudImgUrlBaseV3 + 'The_Ashes_Logo.svg',
    // Tnpl_quicklink_v3: cloudImgUrlBaseV3 + 'Tamil_Nadu_Premier_League.jpeg',
    // Lpf_quicklink_v3: cloudImgUrlBaseV3 + 'LPF_logo.svg',
    // Mlc_quicklink_v3: cloudImgUrlBaseV3 + 'MLC_logo.svg',
    // SerieA_quicklink_v3: cloudImgUrlBaseV3 + 'serieA.png',
    // NBA_quicklink_v3: cloudImgUrlBaseV3 + 'NBA.png',
    // PBA_quicklink_v3: cloudImgUrlBaseV3 + 'PBA.png',
    // Championship_quicklink_v3: cloudImgUrlBaseV3 + 'Championship.png',
    Down_arrow: cloudImgUrlBaseV3 + 'downArrow.png',

    // v3 footer
    casino_v3: cloudImgUrlBaseV3 + 'international_casino.svg',
    home_v3: cloudImgUrlBaseV3 + 'international_home.svg',
    inplay_v3: cloudImgUrlBaseV3 + 'international_soccer.svg',
    statement_v3: cloudImgUrlBaseV3 + 'international_statement.svg',
    my_v3: cloudImgUrlBaseV3 + 'international_my.svg',
    RNG_v3: cloudImgUrlBaseV3 + 'international_RNG.svg',

    //stream
    v3_streamError_ddc08c: cloudImgUrlBaseV3 + 'v3_streamError_ddc08c.svg',
    streaming_333: cloudImgUrlBaseV3 + 'streaming_333.svg',
    streaming_ddc08c: cloudImgUrlBaseV3 + 'streaming_ddc08c.svg',
    streaming_fullscreen: cloudImgUrlBaseV3 + 'streaming-fullscreen.svg',
    streaming_iconizer_compress:
      cloudImgUrlBaseV3 + 'streaming-iconizer-compress.svg',
    streaming_fancy_arrow: cloudImgUrlBaseV3 + 'streaming-fancy-arrow.svg',
    streaming_hamburger: cloudImgUrlBaseV3 + 'streaming-hamburger.svg',
    streaming_video_pause: cloudImgUrlBaseV3 + 'streaming-video-pause.svg',
    streaming_video_stop: cloudImgUrlBaseV3 + 'streaming-video-stop.svg',
    streaming_video_play: cloudImgUrlBaseV3 + 'streaming-video-play.svg',
    streaming_visible_open_icon:
      cloudImgUrlBaseV3 + 'streaming-visible-open-icon.svg',
    streaming_keyboard_arrow:
      cloudImgUrlBaseV3 + 'streaming-keyboard-arrow.svg',
    streaming_close_icon: cloudImgUrlBaseV3 + 'streaming-close-icon.svg',
    streaming_visible_off_icon:
      cloudImgUrlBaseV3 + 'streaming-visible-off-icon.svg',
    streaming_video_sound_muted_icon:
      cloudImgUrlBaseV3 + 'streaming-video-sound-muted-icon.svg',
    streaming_video_sound_off_icon:
      cloudImgUrlBaseV3 + 'streaming-video-sound-off-icon.svg',
    streaming_phone_icon: cloudImgUrlBaseV3 + 'streaming-phone-icon.svg',
    streaming_fit_icon: cloudImgUrlBaseV3 + 'streaming-fit-icon.svg',
    portraitScreenVertical: cloudImgUrlBaseV3 + 'portraitScreenVertical.svg',
    portraitScreen: cloudImgUrlBaseV3 + 'portraitScreen.svg',
    nothing_start: cloudImgUrlBaseV3 + 'nothing_star.svg',
    news_xx: cloudImgUrlBaseV3 + 'news_xx.svg',

    // burger
    v3_betFlix_icon: cloudImgUrlBaseV3 + 'v3_betFlix_icon.svg',
    v3_burger_enter_icon: cloudImgUrlBaseV3 + 'v3_burger_enter_icon.svg',
    v3_burger_plus_c4c4c4: cloudImgUrlBaseV3 + 'v3_burger_plus_c4c4c4.svg',
    v3_burger_dropDown_ddc08c:
      cloudImgUrlBaseV3 + 'v3_burger_dropDown_ddc08c.svg',
    v3_burger_dropDown_c4c4c4:
      cloudImgUrlBaseV3 + 'v3_burger_dropDown_c4c4c4.svg',
    v3_burger_dropDown_999: cloudImgUrlBaseV3 + 'v3_burger_dropDown_999.svg',

    // sponsor
    v3_page_Spanish_LaLiga: cloudImgUrlBaseV3 + 'v3_page_Spanish_LaLiga.png',
    v3_page_Italian_Serie_A: cloudImgUrlBaseV3 + 'v3_page_Italian_Serie_A.png',
    v3_page_S_S_LAZIO: cloudImgUrlBaseV3 + 'v3_page_S_S_LAZIO.png',

    ClassificaSerieA: cloudImgUrlBaseV3 + 'ClassificaSerieA.png',
    bundesliga: cloudImgUrlBaseV3 + 'bundesliga.png',

    // VERSION 3 FIFA
    FIFA_arrow: cloudImgUrlBaseV3 + 'FIFA_arrow.svg',
    FIFA_fire: cloudImgUrlBaseV3 + 'FIFA_fire.svg',

    // v3 Notification
    NewOddDirection: cloudImgUrlBaseV3 + 'NewOddDirection_v3.svg',
    //pc orderslip
    wallet: cloudImgUrlBaseV3 + 'wallet.svg',
    iconizer_eye: cloudImgUrlBaseV3 + 'iconizer_eye.svg',
    quicklink_fire: cloudImgUrlBaseV3 + 'Quicklink_fire.gif',
    live_page: cloudImgUrlBaseV3 + 'live_page.svg',
    home: cloudImgUrlBaseV3 + 'home.svg',

    bonus_tutor: cloudImgUrlBaseV3 + 'Group870.png',

    // v3 Nation
    vi: cloudImgUrlBaseV3 + 'flag/vi.png',
    en: cloudImgUrlBaseV3 + 'flag/en.png',
    hi: cloudImgUrlBaseV3 + 'flag/hi.png',
    zh: cloudImgUrlBaseV3 + 'flag/zh.png',
    th: cloudImgUrlBaseV3 + 'flag/th.png',
    pt: cloudImgUrlBaseV3 + 'flag/pt.png',
    bd: cloudImgUrlBaseV3 + 'flag/bd.png',
    tr: cloudImgUrlBaseV3 + 'flag/tr.svg',
  },
};

export default cloudImg;
